[project]
name = "smartscreen"
version = "0.1.0"
dependencies = [
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
    "python-multipart>=0.0.9",
    "PyMuPDF>=1.24.10",
    "httpx>=0.27.2",
    "python-jose[cryptography]>=3.3.0",
    "cachetools>=5.3.3",
    "ruff>=0.13.1",
]
